/**
 * Email Template Service
 * Customizable templates for compliance reports, incident alerts, and policy notifications
 * MediVac One v5.5
 */

import AsyncStorage from '@react-native-async-storage/async-storage';

// Storage keys
const STORAGE_KEYS = {
  TEMPLATES: 'medivac_email_templates',
  TEMPLATE_VERSIONS: 'medivac_template_versions',
  TEMPLATE_USAGE: 'medivac_template_usage',
};

// Types
export type TemplateCategory = 'compliance' | 'incident' | 'policy' | 'general' | 'clinical' | 'administrative';
export type TemplateStatus = 'draft' | 'active' | 'archived';

export interface TemplateVariable {
  name: string;
  description: string;
  defaultValue: string;
  required: boolean;
  type: 'text' | 'number' | 'date' | 'list' | 'boolean';
}

export interface EmailTemplate {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  subject: string;
  bodyHtml: string;
  bodyText: string;
  variables: TemplateVariable[];
  status: TemplateStatus;
  version: number;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  lastUsedAt?: string;
  usageCount: number;
}

export interface TemplateVersion {
  id: string;
  templateId: string;
  version: number;
  subject: string;
  bodyHtml: string;
  bodyText: string;
  variables: TemplateVariable[];
  createdAt: string;
  createdBy: string;
  changeNotes: string;
}

export interface TemplatePreview {
  subject: string;
  bodyHtml: string;
  bodyText: string;
  missingVariables: string[];
}

export interface TemplateUsageRecord {
  id: string;
  templateId: string;
  usedAt: string;
  usedBy: string;
  recipientCount: number;
  success: boolean;
  errorMessage?: string;
}

// Default templates
const DEFAULT_TEMPLATES: Partial<EmailTemplate>[] = [
  {
    name: 'HIPAA Compliance Report',
    description: 'Monthly HIPAA compliance status report',
    category: 'compliance',
    subject: 'HIPAA Compliance Report - {{month}} {{year}}',
    bodyHtml: `
      <h1>HIPAA Compliance Report</h1>
      <p>Report Period: {{month}} {{year}}</p>
      <h2>Summary</h2>
      <p>Overall Compliance Score: <strong>{{complianceScore}}%</strong></p>
      <h2>Key Findings</h2>
      <ul>
        <li>Total Audits: {{totalAudits}}</li>
        <li>Passed: {{passedAudits}}</li>
        <li>Failed: {{failedAudits}}</li>
      </ul>
      <h2>Recommendations</h2>
      <p>{{recommendations}}</p>
      <p>Generated by MediVac One on {{generatedDate}}</p>
    `,
    bodyText: 'HIPAA Compliance Report\n\nReport Period: {{month}} {{year}}\n\nOverall Compliance Score: {{complianceScore}}%\n\nTotal Audits: {{totalAudits}}\nPassed: {{passedAudits}}\nFailed: {{failedAudits}}\n\nRecommendations:\n{{recommendations}}\n\nGenerated by MediVac One on {{generatedDate}}',
    variables: [
      { name: 'month', description: 'Report month', defaultValue: 'January', required: true, type: 'text' },
      { name: 'year', description: 'Report year', defaultValue: '2026', required: true, type: 'text' },
      { name: 'complianceScore', description: 'Overall compliance percentage', defaultValue: '95', required: true, type: 'number' },
      { name: 'totalAudits', description: 'Total number of audits', defaultValue: '50', required: true, type: 'number' },
      { name: 'passedAudits', description: 'Number of passed audits', defaultValue: '48', required: true, type: 'number' },
      { name: 'failedAudits', description: 'Number of failed audits', defaultValue: '2', required: true, type: 'number' },
      { name: 'recommendations', description: 'Compliance recommendations', defaultValue: 'Continue current practices', required: false, type: 'text' },
      { name: 'generatedDate', description: 'Report generation date', defaultValue: new Date().toLocaleDateString(), required: true, type: 'date' },
    ],
    tags: ['hipaa', 'compliance', 'monthly'],
  },
  {
    name: 'Security Incident Alert',
    description: 'Immediate notification for security incidents',
    category: 'incident',
    subject: '🚨 SECURITY ALERT: {{incidentType}} Detected - {{severity}}',
    bodyHtml: `
      <div style="background-color: #FEE2E2; padding: 20px; border-radius: 8px;">
        <h1 style="color: #DC2626;">⚠️ Security Incident Alert</h1>
        <table style="width: 100%;">
          <tr><td><strong>Incident Type:</strong></td><td>{{incidentType}}</td></tr>
          <tr><td><strong>Severity:</strong></td><td style="color: {{severityColor}};">{{severity}}</td></tr>
          <tr><td><strong>Detected At:</strong></td><td>{{detectedAt}}</td></tr>
          <tr><td><strong>Affected Systems:</strong></td><td>{{affectedSystems}}</td></tr>
          <tr><td><strong>Status:</strong></td><td>{{status}}</td></tr>
        </table>
        <h2>Description</h2>
        <p>{{description}}</p>
        <h2>Immediate Actions Required</h2>
        <p>{{actions}}</p>
        <p style="margin-top: 20px;"><a href="{{dashboardUrl}}" style="background-color: #DC2626; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">View in Dashboard</a></p>
      </div>
    `,
    bodyText: 'SECURITY INCIDENT ALERT\n\nIncident Type: {{incidentType}}\nSeverity: {{severity}}\nDetected At: {{detectedAt}}\nAffected Systems: {{affectedSystems}}\nStatus: {{status}}\n\nDescription:\n{{description}}\n\nImmediate Actions Required:\n{{actions}}\n\nView in Dashboard: {{dashboardUrl}}',
    variables: [
      { name: 'incidentType', description: 'Type of security incident', defaultValue: 'Unauthorized Access', required: true, type: 'text' },
      { name: 'severity', description: 'Incident severity level', defaultValue: 'HIGH', required: true, type: 'text' },
      { name: 'severityColor', description: 'Color for severity display', defaultValue: '#DC2626', required: false, type: 'text' },
      { name: 'detectedAt', description: 'Detection timestamp', defaultValue: new Date().toISOString(), required: true, type: 'date' },
      { name: 'affectedSystems', description: 'List of affected systems', defaultValue: 'Authentication Server', required: true, type: 'text' },
      { name: 'status', description: 'Current incident status', defaultValue: 'Investigating', required: true, type: 'text' },
      { name: 'description', description: 'Detailed incident description', defaultValue: 'Multiple failed login attempts detected', required: true, type: 'text' },
      { name: 'actions', description: 'Required immediate actions', defaultValue: 'Review access logs and verify user accounts', required: true, type: 'text' },
      { name: 'dashboardUrl', description: 'Link to security dashboard', defaultValue: 'https://medivac.one/security', required: false, type: 'text' },
    ],
    tags: ['security', 'incident', 'alert', 'urgent'],
  },
  {
    name: 'Policy Update Notification',
    description: 'Notify staff of policy changes',
    category: 'policy',
    subject: '📋 Policy Update: {{policyName}} - Effective {{effectiveDate}}',
    bodyHtml: `
      <h1>Policy Update Notification</h1>
      <div style="background-color: #EFF6FF; padding: 15px; border-radius: 8px; margin: 20px 0;">
        <h2 style="margin-top: 0;">{{policyName}}</h2>
        <p><strong>Department:</strong> {{department}}</p>
        <p><strong>Effective Date:</strong> {{effectiveDate}}</p>
        <p><strong>Version:</strong> {{version}}</p>
      </div>
      <h3>Summary of Changes</h3>
      <p>{{changeSummary}}</p>
      <h3>Key Points</h3>
      {{keyPoints}}
      <h3>Action Required</h3>
      <p>{{actionRequired}}</p>
      <p style="margin-top: 20px;">
        <a href="{{policyUrl}}" style="background-color: #3B82F6; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">View Full Policy</a>
        <a href="{{acknowledgeUrl}}" style="background-color: #10B981; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; margin-left: 10px;">Acknowledge</a>
      </p>
    `,
    bodyText: 'Policy Update Notification\n\nPolicy: {{policyName}}\nDepartment: {{department}}\nEffective Date: {{effectiveDate}}\nVersion: {{version}}\n\nSummary of Changes:\n{{changeSummary}}\n\nKey Points:\n{{keyPoints}}\n\nAction Required:\n{{actionRequired}}\n\nView Full Policy: {{policyUrl}}\nAcknowledge: {{acknowledgeUrl}}',
    variables: [
      { name: 'policyName', description: 'Name of the policy', defaultValue: 'Data Access Policy', required: true, type: 'text' },
      { name: 'department', description: 'Affected department', defaultValue: 'All Departments', required: true, type: 'text' },
      { name: 'effectiveDate', description: 'When policy takes effect', defaultValue: new Date().toLocaleDateString(), required: true, type: 'date' },
      { name: 'version', description: 'Policy version number', defaultValue: '2.0', required: true, type: 'text' },
      { name: 'changeSummary', description: 'Summary of what changed', defaultValue: 'Updated access control requirements', required: true, type: 'text' },
      { name: 'keyPoints', description: 'Key points as HTML list', defaultValue: '<ul><li>New MFA requirements</li><li>Updated session timeouts</li></ul>', required: false, type: 'text' },
      { name: 'actionRequired', description: 'What staff need to do', defaultValue: 'Review and acknowledge by the effective date', required: true, type: 'text' },
      { name: 'policyUrl', description: 'Link to full policy document', defaultValue: 'https://medivac.one/policies', required: false, type: 'text' },
      { name: 'acknowledgeUrl', description: 'Link to acknowledge policy', defaultValue: 'https://medivac.one/acknowledge', required: false, type: 'text' },
    ],
    tags: ['policy', 'notification', 'compliance'],
  },
  {
    name: 'Daily Clinical Summary',
    description: 'Daily summary of clinical activities',
    category: 'clinical',
    subject: '📊 Daily Clinical Summary - {{date}}',
    bodyHtml: `
      <h1>Daily Clinical Summary</h1>
      <p>Date: {{date}}</p>
      <h2>Patient Statistics</h2>
      <table style="width: 100%; border-collapse: collapse;">
        <tr style="background-color: #F3F4F6;"><td style="padding: 10px; border: 1px solid #E5E7EB;"><strong>Admissions</strong></td><td style="padding: 10px; border: 1px solid #E5E7EB;">{{admissions}}</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #E5E7EB;"><strong>Discharges</strong></td><td style="padding: 10px; border: 1px solid #E5E7EB;">{{discharges}}</td></tr>
        <tr style="background-color: #F3F4F6;"><td style="padding: 10px; border: 1px solid #E5E7EB;"><strong>Current Census</strong></td><td style="padding: 10px; border: 1px solid #E5E7EB;">{{census}}</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #E5E7EB;"><strong>Surgeries</strong></td><td style="padding: 10px; border: 1px solid #E5E7EB;">{{surgeries}}</td></tr>
        <tr style="background-color: #F3F4F6;"><td style="padding: 10px; border: 1px solid #E5E7EB;"><strong>Emergency Cases</strong></td><td style="padding: 10px; border: 1px solid #E5E7EB;">{{emergencies}}</td></tr>
      </table>
      <h2>Alerts & Notifications</h2>
      <p>{{alerts}}</p>
      <h2>Tomorrow's Schedule</h2>
      <p>{{schedule}}</p>
    `,
    bodyText: 'Daily Clinical Summary\n\nDate: {{date}}\n\nPatient Statistics:\n- Admissions: {{admissions}}\n- Discharges: {{discharges}}\n- Current Census: {{census}}\n- Surgeries: {{surgeries}}\n- Emergency Cases: {{emergencies}}\n\nAlerts & Notifications:\n{{alerts}}\n\nTomorrow\'s Schedule:\n{{schedule}}',
    variables: [
      { name: 'date', description: 'Report date', defaultValue: new Date().toLocaleDateString(), required: true, type: 'date' },
      { name: 'admissions', description: 'Number of admissions', defaultValue: '12', required: true, type: 'number' },
      { name: 'discharges', description: 'Number of discharges', defaultValue: '8', required: true, type: 'number' },
      { name: 'census', description: 'Current patient count', defaultValue: '47', required: true, type: 'number' },
      { name: 'surgeries', description: 'Number of surgeries', defaultValue: '5', required: true, type: 'number' },
      { name: 'emergencies', description: 'Emergency cases', defaultValue: '3', required: true, type: 'number' },
      { name: 'alerts', description: 'Important alerts', defaultValue: 'No critical alerts', required: false, type: 'text' },
      { name: 'schedule', description: 'Tomorrow\'s key events', defaultValue: '3 scheduled surgeries', required: false, type: 'text' },
    ],
    tags: ['clinical', 'daily', 'summary'],
  },
  {
    name: 'Staff Announcement',
    description: 'General staff announcements and updates',
    category: 'administrative',
    subject: '📢 {{announcementType}}: {{title}}',
    bodyHtml: `
      <div style="background-color: #F0FDF4; padding: 20px; border-radius: 8px;">
        <h1>{{title}}</h1>
        <p style="color: #6B7280; font-size: 14px;">{{announcementType}} | {{date}}</p>
        <div style="margin: 20px 0;">
          {{content}}
        </div>
        <p><strong>Contact:</strong> {{contactPerson}} ({{contactEmail}})</p>
      </div>
    `,
    bodyText: '{{announcementType}}: {{title}}\n\nDate: {{date}}\n\n{{content}}\n\nContact: {{contactPerson}} ({{contactEmail}})',
    variables: [
      { name: 'announcementType', description: 'Type of announcement', defaultValue: 'General Announcement', required: true, type: 'text' },
      { name: 'title', description: 'Announcement title', defaultValue: 'Important Update', required: true, type: 'text' },
      { name: 'date', description: 'Announcement date', defaultValue: new Date().toLocaleDateString(), required: true, type: 'date' },
      { name: 'content', description: 'Main announcement content', defaultValue: 'Please be advised of the following update...', required: true, type: 'text' },
      { name: 'contactPerson', description: 'Contact person name', defaultValue: 'HR Department', required: false, type: 'text' },
      { name: 'contactEmail', description: 'Contact email', defaultValue: 'hr@medivac.one', required: false, type: 'text' },
    ],
    tags: ['announcement', 'staff', 'general'],
  },
];

class EmailTemplateService {
  private templates: EmailTemplate[] = [];
  private versions: TemplateVersion[] = [];
  private usageRecords: TemplateUsageRecord[] = [];

  async initialize(): Promise<void> {
    await this.loadTemplates();
    await this.loadVersions();
    await this.loadUsageRecords();

    // Create default templates if none exist
    if (this.templates.length === 0) {
      await this.createDefaultTemplates();
    }
  }

  private async loadTemplates(): Promise<void> {
    try {
      const data = await AsyncStorage.getItem(STORAGE_KEYS.TEMPLATES);
      if (data) {
        this.templates = JSON.parse(data);
      }
    } catch (error) {
      console.error('Failed to load email templates:', error);
    }
  }

  private async loadVersions(): Promise<void> {
    try {
      const data = await AsyncStorage.getItem(STORAGE_KEYS.TEMPLATE_VERSIONS);
      if (data) {
        this.versions = JSON.parse(data);
      }
    } catch (error) {
      console.error('Failed to load template versions:', error);
    }
  }

  private async loadUsageRecords(): Promise<void> {
    try {
      const data = await AsyncStorage.getItem(STORAGE_KEYS.TEMPLATE_USAGE);
      if (data) {
        this.usageRecords = JSON.parse(data);
      }
    } catch (error) {
      console.error('Failed to load template usage records:', error);
    }
  }

  private async saveTemplates(): Promise<void> {
    await AsyncStorage.setItem(STORAGE_KEYS.TEMPLATES, JSON.stringify(this.templates));
  }

  private async saveVersions(): Promise<void> {
    await AsyncStorage.setItem(STORAGE_KEYS.TEMPLATE_VERSIONS, JSON.stringify(this.versions));
  }

  private async saveUsageRecords(): Promise<void> {
    await AsyncStorage.setItem(STORAGE_KEYS.TEMPLATE_USAGE, JSON.stringify(this.usageRecords));
  }

  private async createDefaultTemplates(): Promise<void> {
    for (const template of DEFAULT_TEMPLATES) {
      await this.createTemplate(template);
    }
  }

  /**
   * Get all templates
   */
  getTemplates(): EmailTemplate[] {
    return [...this.templates];
  }

  /**
   * Get templates by category
   */
  getTemplatesByCategory(category: TemplateCategory): EmailTemplate[] {
    return this.templates.filter(t => t.category === category);
  }

  /**
   * Get template by ID
   */
  getTemplate(id: string): EmailTemplate | null {
    return this.templates.find(t => t.id === id) || null;
  }

  /**
   * Create new template
   */
  async createTemplate(template: Partial<EmailTemplate>): Promise<EmailTemplate> {
    const now = new Date().toISOString();
    const newTemplate: EmailTemplate = {
      id: `template_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      name: template.name || 'New Template',
      description: template.description || '',
      category: template.category || 'general',
      subject: template.subject || '',
      bodyHtml: template.bodyHtml || '',
      bodyText: template.bodyText || '',
      variables: template.variables || [],
      status: template.status || 'draft',
      version: 1,
      tags: template.tags || [],
      createdAt: now,
      updatedAt: now,
      createdBy: template.createdBy || 'system',
      usageCount: 0,
    };

    this.templates.push(newTemplate);
    await this.saveTemplates();

    // Create initial version
    await this.createVersion(newTemplate.id, 'Initial version');

    return newTemplate;
  }

  /**
   * Update template
   */
  async updateTemplate(id: string, updates: Partial<EmailTemplate>, changeNotes?: string): Promise<EmailTemplate> {
    const index = this.templates.findIndex(t => t.id === id);
    if (index < 0) {
      throw new Error('Template not found');
    }

    const template = this.templates[index];
    const hasContentChanges = 
      updates.subject !== undefined && updates.subject !== template.subject ||
      updates.bodyHtml !== undefined && updates.bodyHtml !== template.bodyHtml ||
      updates.bodyText !== undefined && updates.bodyText !== template.bodyText ||
      updates.variables !== undefined;

    this.templates[index] = {
      ...template,
      ...updates,
      version: hasContentChanges ? template.version + 1 : template.version,
      updatedAt: new Date().toISOString(),
    };

    await this.saveTemplates();

    // Create new version if content changed
    if (hasContentChanges) {
      await this.createVersion(id, changeNotes || 'Updated template');
    }

    return this.templates[index];
  }

  /**
   * Delete template
   */
  async deleteTemplate(id: string): Promise<boolean> {
    const index = this.templates.findIndex(t => t.id === id);
    if (index < 0) {
      return false;
    }

    this.templates.splice(index, 1);
    await this.saveTemplates();

    // Also delete versions
    this.versions = this.versions.filter(v => v.templateId !== id);
    await this.saveVersions();

    return true;
  }

  /**
   * Create template version
   */
  private async createVersion(templateId: string, changeNotes: string): Promise<TemplateVersion> {
    const template = this.getTemplate(templateId);
    if (!template) {
      throw new Error('Template not found');
    }

    const version: TemplateVersion = {
      id: `version_${Date.now()}`,
      templateId,
      version: template.version,
      subject: template.subject,
      bodyHtml: template.bodyHtml,
      bodyText: template.bodyText,
      variables: [...template.variables],
      createdAt: new Date().toISOString(),
      createdBy: 'system',
      changeNotes,
    };

    this.versions.push(version);
    await this.saveVersions();

    return version;
  }

  /**
   * Get template versions
   */
  getTemplateVersions(templateId: string): TemplateVersion[] {
    return this.versions
      .filter(v => v.templateId === templateId)
      .sort((a, b) => b.version - a.version);
  }

  /**
   * Restore template to specific version
   */
  async restoreVersion(templateId: string, versionId: string): Promise<EmailTemplate> {
    const version = this.versions.find(v => v.id === versionId && v.templateId === templateId);
    if (!version) {
      throw new Error('Version not found');
    }

    return this.updateTemplate(templateId, {
      subject: version.subject,
      bodyHtml: version.bodyHtml,
      bodyText: version.bodyText,
      variables: version.variables,
    }, `Restored to version ${version.version}`);
  }

  /**
   * Preview template with variables
   */
  previewTemplate(templateId: string, variableValues: Record<string, string>): TemplatePreview {
    const template = this.getTemplate(templateId);
    if (!template) {
      throw new Error('Template not found');
    }

    const missingVariables: string[] = [];
    let subject = template.subject;
    let bodyHtml = template.bodyHtml;
    let bodyText = template.bodyText;

    // Replace variables
    for (const variable of template.variables) {
      const value = variableValues[variable.name] || variable.defaultValue;
      const placeholder = `{{${variable.name}}}`;

      if (variable.required && !variableValues[variable.name] && !variable.defaultValue) {
        missingVariables.push(variable.name);
      }

      subject = subject.replace(new RegExp(placeholder, 'g'), value);
      bodyHtml = bodyHtml.replace(new RegExp(placeholder, 'g'), value);
      bodyText = bodyText.replace(new RegExp(placeholder, 'g'), value);
    }

    return {
      subject,
      bodyHtml,
      bodyText,
      missingVariables,
    };
  }

  /**
   * Record template usage
   */
  async recordUsage(templateId: string, recipientCount: number, success: boolean, errorMessage?: string): Promise<void> {
    const record: TemplateUsageRecord = {
      id: `usage_${Date.now()}`,
      templateId,
      usedAt: new Date().toISOString(),
      usedBy: 'system',
      recipientCount,
      success,
      errorMessage,
    };

    this.usageRecords.push(record);
    await this.saveUsageRecords();

    // Update template usage count
    const template = this.getTemplate(templateId);
    if (template) {
      await this.updateTemplate(templateId, {
        usageCount: template.usageCount + 1,
        lastUsedAt: record.usedAt,
      });
    }
  }

  /**
   * Get template usage statistics
   */
  getUsageStats(templateId?: string): {
    totalUsage: number;
    successRate: number;
    averageRecipients: number;
    usageByCategory: Record<TemplateCategory, number>;
  } {
    const records = templateId 
      ? this.usageRecords.filter(r => r.templateId === templateId)
      : this.usageRecords;

    const totalUsage = records.length;
    const successCount = records.filter(r => r.success).length;
    const totalRecipients = records.reduce((sum, r) => sum + r.recipientCount, 0);

    const usageByCategory: Record<TemplateCategory, number> = {
      compliance: 0,
      incident: 0,
      policy: 0,
      general: 0,
      clinical: 0,
      administrative: 0,
    };

    for (const record of records) {
      const template = this.getTemplate(record.templateId);
      if (template) {
        usageByCategory[template.category]++;
      }
    }

    return {
      totalUsage,
      successRate: totalUsage > 0 ? (successCount / totalUsage) * 100 : 0,
      averageRecipients: totalUsage > 0 ? totalRecipients / totalUsage : 0,
      usageByCategory,
    };
  }

  /**
   * Duplicate template
   */
  async duplicateTemplate(id: string, newName?: string): Promise<EmailTemplate> {
    const template = this.getTemplate(id);
    if (!template) {
      throw new Error('Template not found');
    }

    return this.createTemplate({
      ...template,
      name: newName || `${template.name} (Copy)`,
      status: 'draft',
    });
  }

  /**
   * Export templates
   */
  exportTemplates(ids?: string[]): string {
    const templates = ids 
      ? this.templates.filter(t => ids.includes(t.id))
      : this.templates;

    return JSON.stringify(templates, null, 2);
  }

  /**
   * Import templates
   */
  async importTemplates(jsonData: string): Promise<{ imported: number; errors: string[] }> {
    const errors: string[] = [];
    let imported = 0;

    try {
      const templates = JSON.parse(jsonData) as Partial<EmailTemplate>[];
      
      for (const template of templates) {
        try {
          // Remove ID to create new template
          const { id, ...templateData } = template;
          await this.createTemplate(templateData);
          imported++;
        } catch (error) {
          errors.push(`Failed to import "${template.name}": ${error}`);
        }
      }
    } catch (error) {
      errors.push(`Invalid JSON format: ${error}`);
    }

    return { imported, errors };
  }

  /**
   * Search templates
   */
  searchTemplates(query: string): EmailTemplate[] {
    const lowerQuery = query.toLowerCase();
    return this.templates.filter(t => 
      t.name.toLowerCase().includes(lowerQuery) ||
      t.description.toLowerCase().includes(lowerQuery) ||
      t.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
    );
  }
}

export const emailTemplateService = new EmailTemplateService();
