/**
 * Inventory Auto-Reorder Service
 * MediVac One v3.0 - Smart Inventory Management
 * 
 * Automatic purchase order generation when supplies reach reorder thresholds
 */

// Types
export type ItemCategory = 'medications' | 'supplies' | 'equipment' | 'ppe' | 'surgical' | 'lab' | 'nutrition';
export type StockStatus = 'in_stock' | 'low_stock' | 'critical' | 'out_of_stock' | 'overstocked';
export type OrderStatus = 'draft' | 'pending_approval' | 'approved' | 'submitted' | 'confirmed' | 'shipped' | 'received' | 'cancelled';
export type ReorderStrategy = 'fixed_quantity' | 'days_of_supply' | 'economic_order_quantity' | 'just_in_time';

export interface InventoryItem {
  id: string;
  name: string;
  sku: string;
  category: ItemCategory;
  description: string;
  unit: string;
  currentQuantity: number;
  reorderPoint: number;
  reorderQuantity: number;
  maxQuantity: number;
  minQuantity: number;
  unitCost: number;
  preferredVendorId: string;
  alternateVendorIds: string[];
  location: string;
  expirationDate?: Date;
  lotNumber?: string;
  isControlled: boolean;
  isActive: boolean;
  lastOrdered?: Date;
  lastReceived?: Date;
  averageDailyUsage: number;
  leadTimeDays: number;
  reorderStrategy: ReorderStrategy;
  autoReorderEnabled: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Vendor {
  id: string;
  name: string;
  code: string;
  contactName: string;
  email: string;
  phone: string;
  address: string;
  paymentTerms: string;
  leadTimeDays: number;
  minimumOrderAmount: number;
  isPreferred: boolean;
  isActive: boolean;
  rating: number;
  contractExpiration?: Date;
}

export interface PurchaseOrder {
  id: string;
  orderNumber: string;
  vendorId: string;
  vendorName: string;
  status: OrderStatus;
  items: PurchaseOrderItem[];
  subtotal: number;
  tax: number;
  shipping: number;
  total: number;
  requestedBy: string;
  approvedBy?: string;
  approvedAt?: Date;
  expectedDelivery?: Date;
  actualDelivery?: Date;
  notes?: string;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface PurchaseOrderItem {
  id: string;
  inventoryItemId: string;
  itemName: string;
  sku: string;
  quantity: number;
  unitCost: number;
  totalCost: number;
  receivedQuantity: number;
}

export interface ReorderAlert {
  id: string;
  inventoryItemId: string;
  itemName: string;
  category: ItemCategory;
  currentQuantity: number;
  reorderPoint: number;
  reorderQuantity: number;
  daysOfSupplyRemaining: number;
  status: StockStatus;
  suggestedAction: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  createdAt: Date;
  acknowledgedAt?: Date;
  acknowledgedBy?: string;
}

export interface InventoryAnalytics {
  totalItems: number;
  totalValue: number;
  itemsByCategory: Record<ItemCategory, number>;
  stockStatusSummary: Record<StockStatus, number>;
  pendingOrders: number;
  pendingOrderValue: number;
  reorderAlerts: number;
  criticalAlerts: number;
  expiringItems: number;
  turnoverRate: number;
  averageLeadTime: number;
}

export interface UsageForecast {
  itemId: string;
  itemName: string;
  currentQuantity: number;
  projectedUsage: number[];
  daysUntilReorder: number;
  daysUntilStockout: number;
  recommendedOrderDate: Date;
  recommendedQuantity: number;
}

// Service Implementation
class InventoryAutoReorderServiceImpl {
  private items: Map<string, InventoryItem> = new Map();
  private vendors: Map<string, Vendor> = new Map();
  private orders: Map<string, PurchaseOrder> = new Map();
  private alerts: Map<string, ReorderAlert> = new Map();
  private listeners: Set<(event: InventoryEvent) => void> = new Set();

  constructor() {
    this.initializeVendors();
    this.initializeItems();
    this.initializeSampleOrders();
    this.startAutoReorderCheck();
  }

  private initializeVendors(): void {
    const vendors: Vendor[] = [
      { id: 'V001', name: 'MedSupply Co', code: 'MSC', contactName: 'John Smith', email: 'orders@medsupply.com', phone: '1-800-MED-SUPP', address: '123 Medical Way', paymentTerms: 'Net 30', leadTimeDays: 3, minimumOrderAmount: 100, isPreferred: true, isActive: true, rating: 4.8 },
      { id: 'V002', name: 'PharmaDirect', code: 'PD', contactName: 'Jane Doe', email: 'orders@pharmadirect.com', phone: '1-800-PHARMA', address: '456 Pharma Blvd', paymentTerms: 'Net 45', leadTimeDays: 2, minimumOrderAmount: 250, isPreferred: true, isActive: true, rating: 4.6 },
      { id: 'V003', name: 'Surgical Solutions', code: 'SS', contactName: 'Bob Wilson', email: 'sales@surgicalsol.com', phone: '1-800-SURGERY', address: '789 Surgery Lane', paymentTerms: 'Net 30', leadTimeDays: 5, minimumOrderAmount: 500, isPreferred: false, isActive: true, rating: 4.5 },
      { id: 'V004', name: 'Lab Essentials', code: 'LE', contactName: 'Sarah Chen', email: 'orders@labessentials.com', phone: '1-800-LAB-SUPP', address: '321 Lab Street', paymentTerms: 'Net 30', leadTimeDays: 4, minimumOrderAmount: 150, isPreferred: true, isActive: true, rating: 4.7 },
    ];
    vendors.forEach(v => this.vendors.set(v.id, v));
  }

  private initializeItems(): void {
    const items: InventoryItem[] = [
      { id: 'INV001', name: 'Nitrile Gloves (Medium)', sku: 'GLV-NIT-M', category: 'ppe', description: 'Powder-free nitrile examination gloves', unit: 'box', currentQuantity: 45, reorderPoint: 50, reorderQuantity: 100, maxQuantity: 200, minQuantity: 25, unitCost: 12.99, preferredVendorId: 'V001', alternateVendorIds: ['V002'], location: 'Supply Room A', isControlled: false, isActive: true, averageDailyUsage: 5, leadTimeDays: 3, reorderStrategy: 'fixed_quantity', autoReorderEnabled: true, createdAt: new Date(), updatedAt: new Date() },
      { id: 'INV002', name: 'IV Catheters 20G', sku: 'IV-CATH-20', category: 'supplies', description: '20 gauge IV catheters', unit: 'box', currentQuantity: 15, reorderPoint: 30, reorderQuantity: 50, maxQuantity: 100, minQuantity: 10, unitCost: 45.00, preferredVendorId: 'V001', alternateVendorIds: ['V003'], location: 'Supply Room B', isControlled: false, isActive: true, averageDailyUsage: 3, leadTimeDays: 3, reorderStrategy: 'days_of_supply', autoReorderEnabled: true, createdAt: new Date(), updatedAt: new Date() },
      { id: 'INV003', name: 'Morphine Sulfate 10mg/mL', sku: 'MED-MORPH-10', category: 'medications', description: 'Morphine sulfate injection', unit: 'vial', currentQuantity: 8, reorderPoint: 20, reorderQuantity: 30, maxQuantity: 50, minQuantity: 10, unitCost: 8.50, preferredVendorId: 'V002', alternateVendorIds: [], location: 'Pharmacy Vault', isControlled: true, isActive: true, averageDailyUsage: 2, leadTimeDays: 2, reorderStrategy: 'fixed_quantity', autoReorderEnabled: false, createdAt: new Date(), updatedAt: new Date() },
      { id: 'INV004', name: 'Surgical Masks N95', sku: 'MSK-N95', category: 'ppe', description: 'N95 respirator masks', unit: 'box', currentQuantity: 120, reorderPoint: 100, reorderQuantity: 200, maxQuantity: 500, minQuantity: 50, unitCost: 35.00, preferredVendorId: 'V001', alternateVendorIds: ['V002'], location: 'Supply Room A', isControlled: false, isActive: true, averageDailyUsage: 8, leadTimeDays: 3, reorderStrategy: 'days_of_supply', autoReorderEnabled: true, createdAt: new Date(), updatedAt: new Date() },
      { id: 'INV005', name: 'Blood Collection Tubes (Purple)', sku: 'LAB-BCT-PUR', category: 'lab', description: 'EDTA blood collection tubes', unit: 'box', currentQuantity: 25, reorderPoint: 40, reorderQuantity: 80, maxQuantity: 150, minQuantity: 20, unitCost: 28.00, preferredVendorId: 'V004', alternateVendorIds: [], location: 'Lab Storage', isControlled: false, isActive: true, averageDailyUsage: 4, leadTimeDays: 4, reorderStrategy: 'economic_order_quantity', autoReorderEnabled: true, createdAt: new Date(), updatedAt: new Date() },
      { id: 'INV006', name: 'Suture Kit 3-0 Vicryl', sku: 'SUR-VIC-30', category: 'surgical', description: 'Absorbable suture kit', unit: 'kit', currentQuantity: 5, reorderPoint: 15, reorderQuantity: 25, maxQuantity: 50, minQuantity: 5, unitCost: 125.00, preferredVendorId: 'V003', alternateVendorIds: [], location: 'OR Supply', isControlled: false, isActive: true, averageDailyUsage: 2, leadTimeDays: 5, reorderStrategy: 'just_in_time', autoReorderEnabled: true, createdAt: new Date(), updatedAt: new Date() },
      { id: 'INV007', name: 'Saline 0.9% 1000mL', sku: 'IV-SAL-1000', category: 'medications', description: 'Normal saline IV solution', unit: 'bag', currentQuantity: 200, reorderPoint: 150, reorderQuantity: 300, maxQuantity: 600, minQuantity: 100, unitCost: 3.50, preferredVendorId: 'V002', alternateVendorIds: ['V001'], location: 'IV Room', isControlled: false, isActive: true, averageDailyUsage: 20, leadTimeDays: 2, reorderStrategy: 'days_of_supply', autoReorderEnabled: true, createdAt: new Date(), updatedAt: new Date() },
      { id: 'INV008', name: 'Ensure Nutrition Shake', sku: 'NUT-ENS-VAN', category: 'nutrition', description: 'Vanilla nutrition supplement', unit: 'case', currentQuantity: 12, reorderPoint: 20, reorderQuantity: 40, maxQuantity: 80, minQuantity: 10, unitCost: 45.00, preferredVendorId: 'V001', alternateVendorIds: [], location: 'Nutrition Storage', isControlled: false, isActive: true, averageDailyUsage: 2, leadTimeDays: 3, reorderStrategy: 'fixed_quantity', autoReorderEnabled: true, createdAt: new Date(), updatedAt: new Date() },
    ];
    items.forEach(item => this.items.set(item.id, item));
  }

  private initializeSampleOrders(): void {
    const orders: PurchaseOrder[] = [
      {
        id: 'PO-001',
        orderNumber: 'PO-2024-0001',
        vendorId: 'V001',
        vendorName: 'MedSupply Co',
        status: 'shipped',
        items: [
          { id: 'POI-001', inventoryItemId: 'INV001', itemName: 'Nitrile Gloves (Medium)', sku: 'GLV-NIT-M', quantity: 100, unitCost: 12.99, totalCost: 1299, receivedQuantity: 0 },
        ],
        subtotal: 1299,
        tax: 103.92,
        shipping: 25,
        total: 1427.92,
        requestedBy: 'System',
        approvedBy: 'Admin',
        approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60000),
        expectedDelivery: new Date(Date.now() + 1 * 24 * 60 * 60000),
        isAutoGenerated: true,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60000),
        updatedAt: new Date(),
      },
    ];
    orders.forEach(o => this.orders.set(o.id, o));
  }

  private startAutoReorderCheck(): void {
    // Check for reorder needs every hour
    setInterval(() => this.checkReorderNeeds(), 60 * 60 * 1000);
    // Initial check
    this.checkReorderNeeds();
  }

  // Inventory Management
  async getItems(filters?: { category?: ItemCategory; status?: StockStatus; search?: string }): Promise<InventoryItem[]> {
    let items = Array.from(this.items.values()).filter(i => i.isActive);

    if (filters?.category) {
      items = items.filter(i => i.category === filters.category);
    }
    if (filters?.status) {
      items = items.filter(i => this.getStockStatus(i) === filters.status);
    }
    if (filters?.search) {
      const search = filters.search.toLowerCase();
      items = items.filter(i => 
        i.name.toLowerCase().includes(search) || 
        i.sku.toLowerCase().includes(search)
      );
    }

    return items;
  }

  async getItem(itemId: string): Promise<InventoryItem | null> {
    return this.items.get(itemId) || null;
  }

  getStockStatus(item: InventoryItem): StockStatus {
    if (item.currentQuantity <= 0) return 'out_of_stock';
    if (item.currentQuantity <= item.minQuantity) return 'critical';
    if (item.currentQuantity <= item.reorderPoint) return 'low_stock';
    if (item.currentQuantity >= item.maxQuantity) return 'overstocked';
    return 'in_stock';
  }

  async updateQuantity(itemId: string, quantity: number, reason: string): Promise<InventoryItem | null> {
    const item = this.items.get(itemId);
    if (!item) return null;

    item.currentQuantity = Math.max(0, quantity);
    item.updatedAt = new Date();
    this.items.set(itemId, item);

    // Check if reorder needed
    if (item.autoReorderEnabled && item.currentQuantity <= item.reorderPoint) {
      await this.createReorderAlert(item);
    }

    this.emit({ type: 'quantity_updated', data: { item, reason } });
    return item;
  }

  // Reorder Management
  async checkReorderNeeds(): Promise<ReorderAlert[]> {
    const newAlerts: ReorderAlert[] = [];

    for (const item of this.items.values()) {
      if (!item.isActive || !item.autoReorderEnabled) continue;

      const status = this.getStockStatus(item);
      if (status === 'low_stock' || status === 'critical' || status === 'out_of_stock') {
        // Check if alert already exists
        const existingAlert = Array.from(this.alerts.values()).find(
          a => a.inventoryItemId === item.id && !a.acknowledgedAt
        );

        if (!existingAlert) {
          const alert = await this.createReorderAlert(item);
          newAlerts.push(alert);
        }
      }
    }

    return newAlerts;
  }

  private async createReorderAlert(item: InventoryItem): Promise<ReorderAlert> {
    const daysOfSupply = item.averageDailyUsage > 0 
      ? Math.floor(item.currentQuantity / item.averageDailyUsage)
      : 999;

    const status = this.getStockStatus(item);
    const priority = status === 'out_of_stock' ? 'critical' 
      : status === 'critical' ? 'high'
      : daysOfSupply <= 3 ? 'high'
      : daysOfSupply <= 7 ? 'medium'
      : 'low';

    const alert: ReorderAlert = {
      id: `ALERT-${Date.now()}`,
      inventoryItemId: item.id,
      itemName: item.name,
      category: item.category,
      currentQuantity: item.currentQuantity,
      reorderPoint: item.reorderPoint,
      reorderQuantity: this.calculateReorderQuantity(item),
      daysOfSupplyRemaining: daysOfSupply,
      status,
      suggestedAction: this.getSuggestedAction(item, status),
      priority,
      createdAt: new Date(),
    };

    this.alerts.set(alert.id, alert);
    this.emit({ type: 'reorder_alert', data: alert });

    // Auto-generate PO for critical items
    if (priority === 'critical' && item.autoReorderEnabled && !item.isControlled) {
      await this.autoGeneratePurchaseOrder([item]);
    }

    return alert;
  }

  private calculateReorderQuantity(item: InventoryItem): number {
    switch (item.reorderStrategy) {
      case 'fixed_quantity':
        return item.reorderQuantity;
      case 'days_of_supply':
        return Math.ceil(item.averageDailyUsage * 30); // 30 days supply
      case 'economic_order_quantity':
        // Simplified EOQ calculation
        const annualDemand = item.averageDailyUsage * 365;
        const orderingCost = 25; // Fixed ordering cost
        const holdingCost = item.unitCost * 0.2; // 20% holding cost
        return Math.ceil(Math.sqrt((2 * annualDemand * orderingCost) / holdingCost));
      case 'just_in_time':
        return Math.ceil(item.averageDailyUsage * (item.leadTimeDays + 2)); // Lead time + 2 days buffer
      default:
        return item.reorderQuantity;
    }
  }

  private getSuggestedAction(item: InventoryItem, status: StockStatus): string {
    if (status === 'out_of_stock') {
      return `URGENT: Place emergency order for ${item.reorderQuantity} ${item.unit}(s)`;
    }
    if (status === 'critical') {
      return `Place priority order for ${item.reorderQuantity} ${item.unit}(s) immediately`;
    }
    if (status === 'low_stock') {
      return `Schedule reorder of ${item.reorderQuantity} ${item.unit}(s) within ${item.leadTimeDays} days`;
    }
    return 'Monitor inventory levels';
  }

  async getAlerts(includeAcknowledged: boolean = false): Promise<ReorderAlert[]> {
    let alerts = Array.from(this.alerts.values());
    if (!includeAcknowledged) {
      alerts = alerts.filter(a => !a.acknowledgedAt);
    }
    return alerts.sort((a, b) => {
      const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    });
  }

  async acknowledgeAlert(alertId: string, userId: string): Promise<ReorderAlert | null> {
    const alert = this.alerts.get(alertId);
    if (!alert) return null;

    alert.acknowledgedAt = new Date();
    alert.acknowledgedBy = userId;
    this.alerts.set(alertId, alert);

    return alert;
  }

  // Purchase Order Management
  async autoGeneratePurchaseOrder(items: InventoryItem[]): Promise<PurchaseOrder> {
    // Group items by vendor
    const vendorItems = new Map<string, InventoryItem[]>();
    for (const item of items) {
      const vendorId = item.preferredVendorId;
      if (!vendorItems.has(vendorId)) {
        vendorItems.set(vendorId, []);
      }
      vendorItems.get(vendorId)!.push(item);
    }

    // Create PO for first vendor (in production, would create multiple POs)
    const firstEntry = vendorItems.entries().next().value;
    if (!firstEntry) throw new Error('No items to order');
    const [vendorId, vendorItemsList] = firstEntry;
    const vendor = this.vendors.get(vendorId)!;

    const poItems: PurchaseOrderItem[] = vendorItemsList.map((item: InventoryItem) => ({
      id: `POI-${Date.now()}-${item.id}`,
      inventoryItemId: item.id,
      itemName: item.name,
      sku: item.sku,
      quantity: this.calculateReorderQuantity(item),
      unitCost: item.unitCost,
      totalCost: this.calculateReorderQuantity(item) * item.unitCost,
      receivedQuantity: 0,
    }));

    const subtotal = poItems.reduce((sum, i) => sum + i.totalCost, 0);
    const tax = subtotal * 0.08;
    const shipping = subtotal > 500 ? 0 : 25;

    const po: PurchaseOrder = {
      id: `PO-${Date.now()}`,
      orderNumber: `PO-${new Date().getFullYear()}-${String(this.orders.size + 1).padStart(4, '0')}`,
      vendorId: vendor.id,
      vendorName: vendor.name,
      status: 'pending_approval',
      items: poItems,
      subtotal,
      tax,
      shipping,
      total: subtotal + tax + shipping,
      requestedBy: 'Auto-Reorder System',
      expectedDelivery: new Date(Date.now() + vendor.leadTimeDays * 24 * 60 * 60000),
      isAutoGenerated: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    this.orders.set(po.id, po);
    this.emit({ type: 'po_created', data: po });

    return po;
  }

  async createPurchaseOrder(vendorId: string, items: { itemId: string; quantity: number }[], requestedBy: string): Promise<PurchaseOrder> {
    const vendor = this.vendors.get(vendorId);
    if (!vendor) throw new Error('Vendor not found');

    const poItems: PurchaseOrderItem[] = items.map(({ itemId, quantity }) => {
      const item = this.items.get(itemId)!;
      return {
        id: `POI-${Date.now()}-${itemId}`,
        inventoryItemId: itemId,
        itemName: item.name,
        sku: item.sku,
        quantity,
        unitCost: item.unitCost,
        totalCost: quantity * item.unitCost,
        receivedQuantity: 0,
      };
    });

    const subtotal = poItems.reduce((sum, i) => sum + i.totalCost, 0);
    const tax = subtotal * 0.08;
    const shipping = subtotal > vendor.minimumOrderAmount ? 0 : 25;

    const po: PurchaseOrder = {
      id: `PO-${Date.now()}`,
      orderNumber: `PO-${new Date().getFullYear()}-${String(this.orders.size + 1).padStart(4, '0')}`,
      vendorId: vendor.id,
      vendorName: vendor.name,
      status: 'draft',
      items: poItems,
      subtotal,
      tax,
      shipping,
      total: subtotal + tax + shipping,
      requestedBy,
      expectedDelivery: new Date(Date.now() + vendor.leadTimeDays * 24 * 60 * 60000),
      isAutoGenerated: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    this.orders.set(po.id, po);
    this.emit({ type: 'po_created', data: po });

    return po;
  }

  async getPurchaseOrders(filters?: { status?: OrderStatus; vendorId?: string }): Promise<PurchaseOrder[]> {
    let orders = Array.from(this.orders.values());

    if (filters?.status) {
      orders = orders.filter(o => o.status === filters.status);
    }
    if (filters?.vendorId) {
      orders = orders.filter(o => o.vendorId === filters.vendorId);
    }

    return orders.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  async updatePOStatus(poId: string, status: OrderStatus, userId?: string): Promise<PurchaseOrder | null> {
    const po = this.orders.get(poId);
    if (!po) return null;

    po.status = status;
    po.updatedAt = new Date();

    if (status === 'approved' && userId) {
      po.approvedBy = userId;
      po.approvedAt = new Date();
    }

    if (status === 'received') {
      // Update inventory quantities
      for (const item of po.items) {
        const invItem = this.items.get(item.inventoryItemId);
        if (invItem) {
          invItem.currentQuantity += item.quantity;
          invItem.lastReceived = new Date();
          invItem.updatedAt = new Date();
          this.items.set(invItem.id, invItem);
        }
      }
      po.actualDelivery = new Date();
    }

    this.orders.set(poId, po);
    this.emit({ type: 'po_status_changed', data: po });

    return po;
  }

  // Vendor Management
  async getVendors(): Promise<Vendor[]> {
    return Array.from(this.vendors.values()).filter(v => v.isActive);
  }

  async getVendor(vendorId: string): Promise<Vendor | null> {
    return this.vendors.get(vendorId) || null;
  }

  // Analytics
  async getAnalytics(): Promise<InventoryAnalytics> {
    const items = Array.from(this.items.values()).filter(i => i.isActive);
    const orders = Array.from(this.orders.values());
    const alerts = Array.from(this.alerts.values()).filter(a => !a.acknowledgedAt);

    const totalValue = items.reduce((sum, i) => sum + (i.currentQuantity * i.unitCost), 0);

    const itemsByCategory: Record<ItemCategory, number> = {
      medications: 0, supplies: 0, equipment: 0, ppe: 0, surgical: 0, lab: 0, nutrition: 0
    };
    items.forEach(i => itemsByCategory[i.category]++);

    const stockStatusSummary: Record<StockStatus, number> = {
      in_stock: 0, low_stock: 0, critical: 0, out_of_stock: 0, overstocked: 0
    };
    items.forEach(i => stockStatusSummary[this.getStockStatus(i)]++);

    const pendingOrders = orders.filter(o => ['pending_approval', 'approved', 'submitted', 'confirmed', 'shipped'].includes(o.status));
    const pendingOrderValue = pendingOrders.reduce((sum, o) => sum + o.total, 0);

    const expiringItems = items.filter(i => {
      if (!i.expirationDate) return false;
      const daysUntilExpiry = Math.floor((i.expirationDate.getTime() - Date.now()) / (24 * 60 * 60000));
      return daysUntilExpiry <= 30;
    }).length;

    return {
      totalItems: items.length,
      totalValue,
      itemsByCategory,
      stockStatusSummary,
      pendingOrders: pendingOrders.length,
      pendingOrderValue,
      reorderAlerts: alerts.length,
      criticalAlerts: alerts.filter(a => a.priority === 'critical').length,
      expiringItems,
      turnoverRate: 12.5, // Simplified - would calculate from usage data
      averageLeadTime: items.reduce((sum, i) => sum + i.leadTimeDays, 0) / items.length,
    };
  }

  async getUsageForecast(itemId: string): Promise<UsageForecast | null> {
    const item = this.items.get(itemId);
    if (!item) return null;

    const projectedUsage = Array.from({ length: 30 }, (_, i) => 
      Math.round(item.averageDailyUsage * (0.9 + Math.random() * 0.2))
    );

    const totalProjectedUsage = projectedUsage.reduce((sum, u) => sum + u, 0);
    const daysUntilStockout = item.averageDailyUsage > 0 
      ? Math.floor(item.currentQuantity / item.averageDailyUsage)
      : 999;
    const daysUntilReorder = Math.max(0, daysUntilStockout - item.leadTimeDays);

    return {
      itemId: item.id,
      itemName: item.name,
      currentQuantity: item.currentQuantity,
      projectedUsage,
      daysUntilReorder,
      daysUntilStockout,
      recommendedOrderDate: new Date(Date.now() + daysUntilReorder * 24 * 60 * 60000),
      recommendedQuantity: this.calculateReorderQuantity(item),
    };
  }

  // Event System
  private emit(event: InventoryEvent): void {
    this.listeners.forEach(listener => listener(event));
  }

  subscribe(listener: (event: InventoryEvent) => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }
}

export interface InventoryEvent {
  type: 'quantity_updated' | 'reorder_alert' | 'po_created' | 'po_status_changed';
  data: unknown;
}

// Export singleton
export const InventoryAutoReorderService = new InventoryAutoReorderServiceImpl();
export default InventoryAutoReorderService;
